# package-third-party-numpy-subpackage-random-C-extension-parent-BitGenerator-class-Generator-permutations-shuffle
> [TABLE OF CONTENTS](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top)
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.random import default_rng as newGenBitGenPCG64

In [2]:
from numpy.core import arange as arrayEvenlySpaced
from numpy.core import reshape as arrayNewShape

In [3]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print(newGenBitGenPCG64().shuffle.__doc__) # method shuffle - attr __doc__ - access


        shuffle(x, axis=0)

        Modify a sequence in-place by shuffling its contents.

        The order of sub-arrays is changed but their contents remains the same.

        Parameters
        ----------
        x : array_like
            The array or list to be shuffled.
        axis : int, optional
            The axis which `x` is shuffled along. Default is 0.
            It is only supported on `ndarray` objects.

        Returns
        -------
        None

        Examples
        --------
        >>> rng = np.random.default_rng()
        >>> arr = np.arange(10)
        >>> rng.shuffle(arr)
        >>> arr
        [1 7 5 2 9 4 3 6 0 8] # random

        >>> arr = np.arange(9).reshape((3, 3))
        >>> rng.shuffle(arr)
        >>> arr
        array([[3, 4, 5], # random
               [6, 7, 8],
               [0, 1, 2]])

        >>> arr = np.arange(9).reshape((3, 3))
        >>> rng.shuffle(arr, axis=1)
        >>> arr
        array([[2, 0, 1], # random
               [

In [4]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
nInsObjGBT=newGenBitGenPCG64()

In [5]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(10)

In [6]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray)

In [7]:
nArray

array([0, 2, 4, 9, 5, 1, 7, 6, 8, 3])

In [8]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(9)

In [9]:
# package numpy - subpackage core - C function reshape alias arrayNewShape - call
nArray=arrayNewShape(nArray,(3,3))

In [10]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray)

In [11]:
nArray

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

In [12]:
# package numpy - subpackage random - object Generator - method shuffle - call
nInsObjGBT.shuffle(nArray,axis=1)

In [13]:
nArray

array([[3, 4, 5],
       [6, 7, 8],
       [0, 1, 2]])

#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0] Documentation, "numpy.random.Generator.shuffle," [NumPy](https://web.archive.org/web/20201103103712/https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy-random-generator-shuffle), n.d.
***
# END