# package-third-party-numpy-subpackage-random-C-extension-function-binomial
> [TABLE OF CONTENTS](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top)
***

In [1]:
# b_T_hird_P_arty-imports
import numpy.random

In [2]:
# package numpy - subpackage random - C function binomial - call - attribute __doc__ - access
print(numpy.random.binomial.__doc__)


        binomial(n, p, size=None)

        Draw samples from a binomial distribution.

        Samples are drawn from a binomial distribution with specified
        parameters, n trials and p probability of success where
        n an integer >= 0 and p is in the interval [0,1]. (n may be
        input as a float, but it is truncated to an integer in use)

        .. note::
            New code should use the ``binomial`` method of a ``default_rng()``
            instance instead; see `random-quick-start`.

        Parameters
        ----------
        n : int or array_like of ints
            Parameter of the distribution, >= 0. Floats are also accepted,
            but they will be truncated to integers.
        p : float or array_like of floats
            Parameter of the distribution, >= 0 and <=1.
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  If size is ``None

In [3]:
# Kernel - Restart
exit()

In [1]:
# b_T_hird_P_arty-imports
import numpy as np

- **simulation** - counting the number of times a coin lands on heads - 1 [10]

- `n` - $integer >=0$ - number of trials - $1$ - coin flip is a trial - result in only two possible outcomes - heads or tails - calling heads a success - 1 - tails a failure - 0 [10]

- `p` - $interval [0,1]$ - probability of each trial - probability of success is constant - one half on each trial - $0.5$ [10]

In [2]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p=1,0.5

In [3]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p)

1

In [4]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p)

0

- `size` - each coin flip is a trail - tested one time - single batch - $1$ [10]

In [5]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p,size=1,0.5,1

In [6]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p,size)

array([1])

- `size` - each coin flip is a trail - tested two times - batches - $2$ [10]

In [7]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p,size=1,0.5,2

In [8]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p,size)

array([0, 0])

- `p` - $interval [0,1]$ - probability of each trial - probability of success - $0.7$ - 70% percent of the time its a success - heads - $0.3$ - 30% of the time its a failure - tails [10]

- `size` - each coin flip is a trail - tested ten times - batches - $10$ [10]

In [9]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p,size=1,0.7,10

In [10]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p,size)

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1])

- `n` - $integer >=0$ - number of trials - $1000$ - coin flip is a trial - result in only two possible outcomes - heads or tails - calling heads a success - $1$ - tails a failure - $0$ [10]

- `p` - $interval [0,1]$ - probability of each trial - probability of success is constant - one half on each trial - $0.5$ [10]

- `size` - each coin flip is a trail - tested one time - single batch - $1$ [10]

In [11]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p,size=1000,0.5,1

- in general - reasonable to suspect to see 500 - or - at least around 500 heads - flipping a coin 1000 times - perfectly possible to get 1000 heads - unlikely - but possible - perfectly possible to get 1000 tails - unlikely - but possible [10]

In [12]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p,size)

array([486])

- `n` - $integer >=0$ - number of trials - $2000$ - coin flip is a trial - result in only two possible outcomes - heads or tails - calling heads a success - $1$ - tails a failure - $0$ [10]

- `size` - each coin flip is a trail - tested one-thousand times - batches - $1000$ [10]

In [13]:
# package numpy alias np - subpackage random - C function binomial - arguments
n,p,size=2000,0.5,1000

In [14]:
# package numpy alias np - subpackage random - C function binomial - call
np.random.binomial(n,p,size)

array([ 993, 1029,  981,  997, 1013,  986,  987,  997, 1006, 1024, 1007,
       1010,  982, 1018, 1003, 1040,  971, 1011, 1045, 1008, 1025,  991,
       1034, 1008,  982,  996,  968, 1006, 1014,  990, 1020, 1002,  987,
        952, 1020,  980, 1021, 1028,  988,  992,  971,  997,  982,  996,
       1016,  999,  982, 1027, 1008, 1048,  958, 1006,  979,  993,  960,
        968, 1004, 1018,  982, 1021, 1059,  995, 1009, 1008, 1006, 1004,
        991,  979, 1020, 1025, 1044, 1026, 1017,  958, 1018, 1010,  999,
       1027, 1004, 1012, 1017, 1009,  985, 1019, 1003, 1010,  995, 1017,
        997, 1013, 1013,  978,  969, 1024, 1020, 1001,  984,  979, 1001,
        943, 1029,  963,  999,  995, 1046, 1008,  972, 1024, 1040, 1014,
       1077,  982, 1006,  993,  980, 1009,  970, 1045,  966, 1020, 1017,
        974, 1020, 1004, 1046, 1015, 1035, 1024,  957,  967,  990,  984,
       1005,  998, 1012, 1023, 1031,  995, 1046, 1014,  983, 1019, 1029,
        996, 1000,  986, 1010,  973,  972,  991,  9

***

- refer: [[stochasticism](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top/L8733/blob/master/src/hdp/mls/stochasticism.ipynb)]
- refer: [[package-third-party-seaborn-module-distributions-function-distplot](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top/L8733/blob/master/src/pro/par/pyt/package-third-party-seaborn-module-distributions-function-distplot.ipynb)]

***

***
# END