# package-third-party-numpy-subpackage-random-C-extension-parent-BitGenerator-class-Generator-permutations-permutation
> [TABLE OF CONTENTS](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top)
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.random import default_rng as newGenBitGenPCG64

In [2]:
from numpy.core import arange as arrayEvenlySpaced
from numpy.core import reshape as arrayNewShape

In [3]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
print(newGenBitGenPCG64().permutation.__doc__) # method permutation - attr __doc__ - access


        permutation(x, axis=0)

        Randomly permute a sequence, or return a permuted range.

        Parameters
        ----------
        x : int or array_like
            If `x` is an integer, randomly permute ``np.arange(x)``.
            If `x` is an array, make a copy and shuffle the elements
            randomly.
        axis : int, optional
            The axis which `x` is shuffled along. Default is 0.

        Returns
        -------
        out : ndarray
            Permuted sequence or array range.

        Examples
        --------
        >>> rng = np.random.default_rng()
        >>> rng.permutation(10)
        array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random

        >>> rng.permutation([1, 4, 9, 12, 15])
        array([15,  1,  9,  4, 12]) # random

        >>> arr = np.arange(9).reshape((3, 3))
        >>> rng.permutation(arr)
        array([[6, 7, 8], # random
               [0, 1, 2],
               [3, 4, 5]])

        >>> rng.permutation("abc")
        Traceback

In [4]:
# package numpy - subpackage random - object Generator - method default_rng alias newGenBitGenPCG64 - instantiate
nInsObjGBT=newGenBitGenPCG64()

In [5]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(10)

array([0, 7, 6, 1, 9, 5, 2, 3, 4, 8])

In [6]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation([1,4,9,12,15])

array([15,  9,  4, 12,  1])

In [7]:
# package numpy - subpackage core - C function arange alias arrayEvenlySpaced - call
nArray=arrayEvenlySpaced(9)

In [8]:
# package numpy - subpackage core - C function reshape alias arrayNewShape - call
nArray=arrayNewShape(nArray,(3,3))

In [9]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(nArray)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# package numpy - subpackage random - object Generator - method permutation - call
nInsObjGBT.permutation(nArray,axis=1)

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

#### References
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[0] Documentation, "numpy.random.Generator.permutation," [NumPy](https://web.archive.org/web/20201103112923/https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html#numpy-random-generator-permutation), n.d.
***
# END