# package-third-party-numpy-subpackage-core-C-extension-function-array
> [TABLE OF CONTENTS](https://nbviewer.jupyter.org/github/SeanOhAileasa/fubar-python/blob/main/fubar-python.ipynb#top)
***

In [1]:
# b_T_hird_P_arty-imports
from numpy.core import array as nar

- python list - standard mutable multi-element container - hold many objects - given pythons dynamic typing can create heterogeneous lists - flexibility comes at a cost - more efficient to store data in a fixed-type array - fixed-type numpy-style arrays lack the flexibility of lists but are much more efficient for storing and manipulating data - difference between a dynamic-type list and a fixed type - numpy-style array [9.37]

<img src="img/arrayvlist.png" />

- built-in module - class - array - can be used to create dense arrays of a uniform type - more useful is the object - ndarray - from the package - numpy [9.38]

In [2]:
# package numpy - subpackage core - C function array alias nar - copy - attribute __doc__ - access
print(nar.__doc__)

array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly created array will be in C order (row major) unless 'F' is
        specified,

- unlike python lists - numpy - constrained to arrays that all contain the same type - types do not match - numpy will upcast if possible - integers up-cast to floating point [9.39]

In [3]:
# package numpy - subpackage core - C function array alias nar - call
nar([3.14,2,3,5])

array([3.14, 2.  , 3.  , 5.  ])

- explicitly set - data type - of the resulting array - keyword - dtype [9.39]

In [4]:
# package numpy - subpackage core - C function array alias nar - call
nar([2,3,5,7],dtype="float32")

array([2., 3., 5., 7.], dtype=float32)

- unlike python lists - numpy arrays can explicitly be multi-dimensional - list of lists - inner list treated as rows of the resulting two-dimensional array [9.39] 

In [5]:
# package numpy - subpackage core - C function array alias nar - call
nar([range(nEachValue,nEachValue+3) for nEachValue in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

***
# END